try:
    from langchain_core.pydantic_v1 import BaseModel, Field
except ImportError:
    # Fallback to standard pydantic if langchain_core is outdated/missing (unlikely given requirements)
    from pydantic import BaseModel, Field
from typing import List, Optional, Any

class Requirement(BaseModel):
    """Represents a single parsed requirement from the specification."""
    id: str = Field(..., description="The unique identifier for the requirement (e.g., AC-01)")
    title: str = Field(..., description="The short title of the requirement")
    description: str = Field(..., description="The full natural language description (Given/When/Then)")
    priority: Optional[str] = Field("Normal", description="Priority level if specified")

class RequirementList(BaseModel):
    """Wrapper for a list of requirements, used for LLM structured output parsing."""
    requirements: List[Requirement]

class TestScenario(BaseModel):
    """
    Represents a logical test scenario derived from a requirement.
    Generated by the Requirements Analyst Agent.
    """
    requirement_id: str
    scenario_id: str
    description: str = Field(..., description="High-level description of what is being tested")
    steps: List[str] = Field(..., description="Step-by-step instructions (Given/When/Then)")
    expected_result: str
    test_data: Optional[dict] = Field(None, description="Data needed for the test (payloads, headers)")

class TestCase(BaseModel):
    """Represents a generated Pytest case. Generated by Software Tester Agent."""
    requirement_id: str
    scenario_id: str
    test_function_name: str
    code: str = Field(..., description="The full Python code for the test function")
    description: str = Field(..., description="Docstring content explaining the test")

class TestSuite(BaseModel):
    """Collection of requirements and generated tests."""
    requirements: List[Requirement] = []
    scenarios: List[TestScenario] = []
    tests: List[TestCase] = []
